### PR TITLE
[MRG] Initial app + local server work

### PR DESCRIPTION
**Pull request by SimonBiggs**

### CODE REVIEW

**Comment by SimonBiggs** [comment]
@darcymason @Matthew-Jennings this is now printing the DICOM header when a DICOM file is added to the directory `~/LibreApp/`.

To run it yourself need both the local-server and the web-app running. 

First thing you'll need to download `pyodide`. I've made a rough helper script (which will be improved). To run this change to the `libreapp/app/public/vendor` directory and run `python download.py`.

Within `libreapp/local-server` run `python server.py`. Within `libreapp/app` run `yarn` then `yarn start`. Then drag and drop a DICOM file into the created `LibreApp` directory within your home directory on your machine. This DICOM file will be sent to the web-app, which will then print the header to the page.

Lots of the pieces are quite hacky just to get it up and running.

Of note, the server will currently only work with the live online webapp for Chrome and Edge, not Firefox. To get it working with Firefox a certificate needs to be installed on the local server. We can provide instructions for that (or just ask people to use edge or chrome for the local-server usage).

**Comment by darcymason** [comment]
@SimonBiggs, sounds exciting.  I'll try to  look at this tomorrow night.  Also a bit busy with pydicom at the moment, trying to finalize some things for next release.

**Comment by SimonBiggs** [comment]
Makes sense :) Let me know if you need any help :).

**Comment by darcymason** [comment]
A little later than promised, but ... tried it all, and everything worked fine.  The only little stumble was that I didn't have yarn on my Windows machine, so that entailed a node.js download/install, then the yarn installer.  Otherwise, everything just worked.

Nice!

**Comment by SimonBiggs** [comment]
Thanks :). Once you're happy with it did you want to review/approve and merge?

**Comment by darcymason** [comment]
Ok, I will ... I'm trying to learn my way around a bit first.  A few observations:
* chrome grows to about 1,042,500 K according to Task Manager.  I assume this is Numpy etc., but does that size sound right?
* Trying to drop a second file gives me `Unhandled Rejection (Error): FS error` on the line creating temp.dcm in root.tsx
* I can't stop the local server except by killing the process in Task Manager or closing the cmd box.  Can we catch a ctrl-C in there?

That's it for me tonight... I'll pick it up again tomorrow.

**Comment by darcymason** [comment]
Having another look ... FYI, the reason I mentioned the multiple files issue and killing the server is because I was trying to add my own code in (again, to help make sure I understand things to some extent) and that was difficult to test given those issues.  But we can certainly look at merging in and then refining.  I'll do a code review as best I can...

**Review by darcymason — APPROVED** [review]

**Comment by darcymason** [comment]
> Once you're happy with it did you want to review/approve and merge?

Approved.  It seems I'm not authorized for merging - it makes sense for you to merge anyway, at least for the time being.

Note this is approval without fully understanding everything, It seems to be mostly boilerplate for the webassembly/pyiodide/react setup.  React seems to be at the core of it as you mentioned in #6 - I still would like to understand better what should go in Python vs in React, and how contributor apps would interface.

And back to the size issue I mentioned before -- I see matplotlib, numpy, and pandas - is this where my huge chrome memory use was coming from (or just webassembly and pyiodide themselves)? Is it possible to load a smaller subset, then others as needed (especially for testing)?

**Comment by SimonBiggs** [comment]
> And back to the size issue I mentioned before -- I see matplotlib, numpy, and pandas - is this where my huge chrome memory use was coming from (or just webassembly and pyiodide themselves)? Is it possible to load a smaller subset, then others as needed (especially for testing)?

Yup, certainly can do that. I'll work on that next :).

**Comment by SimonBiggs** [comment]
> It seems I'm not authorized for merging

Ahh, oops. Fixed that now.

**Comment by SimonBiggs** [comment]
> Note this is approval without fully understanding everything, It seems to be mostly boilerplate for the webassembly/pyiodide/react setup.

Yup, it really is just boilerplate.

**Comment by SimonBiggs** [comment]
> I still would like to understand better what should go in Python vs in React

My thoughts on this is to have all underlying algorithm / library code occur within Python. Have all user interface code, and user interface logic occur within React.

**Comment by SimonBiggs** [comment]
> Trying to drop a second file gives me `Unhandled Rejection (Error): FS error` on the line creating temp.dcm in root.tsx

Yup, this is my fault for just saving the DICOM file to `temp.dcm`. The error is probably a "this file already exists" error.

**Comment by SimonBiggs** [comment]
> But we can certainly look at merging in and then refining.

Sounds good. I'll merge, and I'll focus on those three points you initially raised (RAM usage, multiple files, and starting and stopping the server).

With the server, there might be value in setting up a watcher, that reboots the server whenever server code changes.

**Comment by SimonBiggs** [comment]
Sorry for the delays on my end. Needed to prioritise another task. Should get a chance to come back to this in the next couple of nights. ... not working on it at work seriously makes it slow going ...

**Pull request merged**
